//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplesoftRetail
{
    using System;
    using System.Collections.Generic;
    
    public partial class cutomer
    {
        public int CutomerCount { get; set; }
        public int storeID { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
